#import "fragments/EventEntry.gql"
#import "fragments/OfficeEntry.gql"

query EventsQuery($officeId: ID) {
  events(officeId: $officeId) {
    ...EventEntry
    office {
      ...OfficeEntry
    }
    duration
  }
}
