#import "fragments/EventEntry.gql"
#import "fragments/OfficeEntry.gql"
#import "fragments/UserEntry.gql"

query EventsQuery($officeId: ID) {
  currentUser {
    ...UserEntry
    isAdmin
  }
  events(officeId: $officeId) {
    ...EventEntry
    office {
      ...OfficeEntry
    }
    duration
  }
}
