#import "fragments/UserEntry.gql"
#import "fragments/OfficeEntry.gql"

query AppQuery {
  currentUser {
    ...UserEntry
    office {
      ...OfficeEntry
    }
    isAdmin
  }
  offices(sortBy: NAME_ASC) {
    ...OfficeEntry
  }
}
