#import "fragments/UserEntry.gql"
#import "fragments/OfficeEntry.gql"
#import "fragments/UserPreferenceEntry.gql"
#import "fragments/LanguageEntry.gql"

query AppQuery {
  currentUser {
    ...UserEntry
    lastSignInAt
    isAdmin
    office {
      ...OfficeEntry
    }
    preference {
      ...UserPreferenceEntry
    }
  }
  offices(sortBy: NAME_ASC) {
    ...OfficeEntry
  }
  languages {
    ...LanguageEntry
  }
}
