#import "fragments/UserEntry.gql"
#import "fragments/OfficeEntry.gql"

query ReportingQuery($after: Int, $before: Int, $officeId: ID) {
  currentUser {
    ...UserEntry
    office {
      ...OfficeEntry
    }
    isAdmin
  }
  users(officeId: $officeId) {
    ...UserEntry
    hours(after: $after, before: $before)
    office {
      ...OfficeEntry
    }
  }
}
