#import "fragments/UserEntry.gql"
#import "fragments/OfficeEntry.gql"
#import "fragments/OrganizationEntry.gql"

query MyEventsQuery {
  currentUser {
    ...UserEntry
    individualEvents {
      id
      status
      duration
      date
      description
      organization {
        ...OrganizationEntry
      }
      eventType {
        id
        title
      }
      office {
        ...OfficeEntry
      }
    }
    signups {
      event {
        id
        title
        duration
        startsAt
        description
        organization {
          id
          name
        }
        eventType {
          id
          title
        }
        location
      }
    }
  }
  offices(sortBy: NAME_ASC) {
    ...OfficeEntry
  }
  eventTypes {
    id
    title
  }
  organizations {
    ...OrganizationEntry
  }
}
