import '@zendeskgarden/react-avatars/dist/styles.css'
import '@zendeskgarden/react-buttons/dist/styles.css'
import '@zendeskgarden/react-dropdowns/dist/styles.css'
import '@zendeskgarden/react-grid/dist/styles.css'
import '@zendeskgarden/react-modals/dist/styles.css'
import '@zendeskgarden/react-notifications/dist/styles.css'
import '@zendeskgarden/react-tags/dist/styles.css'
