#import "fragments/UserEntry.gql"
#import "fragments/OfficeEntry.gql"

query UserQuery($id: ID!) {
  user(id: $id) {
    ...UserEntry
    office {
      ...OfficeEntry
    }
    timezone
    isAdmin
  }
  offices(sortBy: ALPHABETICAL_ASC) {
    ...OfficeEntry
  }
}
