#import "fragments/EventEntry.gql"
#import "fragments/OfficeEntry.gql"
#import "fragments/UserEntry.gql"

query FetchMoreQuery($after: Int, $before: Int) {
  events(after: $after, before: $before) {
    ...EventEntry
    signupCount
    office {
      ...OfficeEntry
    }
    users {
      ...UserEntry
    }
  }
}
