#import "fragments/UserEntry.gql"
#import "fragments/EventEntry.gql"
#import "fragments/OfficeEntry.gql"
#import "fragments/UserEntry.gql"

query EventsQuery($after: Int, $before: Int, $officeId: ID) {
  currentUser {
    ...UserEntry
    isAdmin
    office {
      ...OfficeEntry
    }
  }
  events(after: $after, before: $before, officeId: $officeId) {
    ...EventEntry
    signupCount
    office {
      ...OfficeEntry
    }
    users {
      ...UserEntry
    }
  }
  offices {
    ...OfficeEntry
  }
}
